name: pr

on: [pull_request, workflow_dispatch]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false